site_name: NWApp Backend
nav:
    - Overview: index.md
    - Installation:
        - MacOS: installation/MacOS.md
    - API:
        - Introduction: api/notes.md
        - Basic: api/basic.md
        - Gateway: api/gateway.md
        - Dashboard: api/dashboard.md
    - Reference:
        - Dependencies: reference/dependencies.md
theme: readthedocs
